on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - run: docker login --username "$DOCKER_USER" --password "$DOCKER_PASS" ghcr.io
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
    - run: python3 -uSm main sync ${{ github.event_name == 'pull_request' && '--dry-run' || '' }}
